# Generated by Django 3.1 on 2020-08-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('material', models.TextField(blank=True, db_column='MATERIAL', null=True)),
                ('descripcion_material', models.TextField(blank=True, db_column='DESCRIPCION_MATERIAL', null=True)),
                ('descripcion_material_enriquecido', models.TextField(blank=True, db_column='DESCRIPCION_MATERIAL_ENRIQUECIDO', null=True)),
                ('descripcion_larga', models.TextField(blank=True, db_column='DESCRIPCION_LARGA', null=True)),
                ('ean', models.CharField(blank=True, db_column='EAN', max_length=30, primary_key=True, serialize=False)),
                ('codigo_talla', models.TextField(blank=True, db_column='CODIGO_TALLA', null=True)),
                ('descripcion_talla', models.TextField(blank=True, db_column='DESCRIPCION_TALLA', null=True)),
                ('codigo_color', models.TextField(blank=True, db_column='CODIGO_COLOR', null=True)),
                ('descripcion_color', models.TextField(blank=True, db_column='DESCRIPCION_COLOR', null=True)),
                ('imagen_pequena', models.TextField(blank=True, db_column='IMAGEN_PEQUENA', null=True)),
                ('imagen_grande', models.TextField(blank=True, db_column='IMAGEN_GRANDE', null=True)),
                ('imagen_frente', models.TextField(blank=True, db_column='IMAGEN_FRENTE', null=True)),
                ('imagen_espalda', models.TextField(blank=True, db_column='IMAGEN_ESPALDA', null=True)),
                ('imagen_detalle', models.TextField(blank=True, db_column='IMAGEN_DETALLE', null=True)),
                ('imagen_detalle2', models.TextField(blank=True, db_column='IMAGEN_DETALLE2', null=True)),
                ('tipo_prenda', models.TextField(blank=True, db_column='TIPO_PRENDA', null=True)),
                ('subgrupo', models.TextField(blank=True, db_column='SUBGRUPO', null=True)),
                ('caracteristica', models.TextField(blank=True, db_column='CARACTERISTICA', null=True)),
                ('marca', models.TextField(blank=True, db_column='MARCA', null=True)),
                ('uso', models.TextField(blank=True, db_column='USO', null=True)),
                ('grupo_destino', models.TextField(blank=True, db_column='GRUPO_DESTINO', null=True)),
                ('genero', models.TextField(blank=True, db_column='GENERO', null=True)),
                ('departamento', models.TextField(blank=True, db_column='DEPARTAMENTO', null=True)),
                ('tags', models.TextField(blank=True, db_column='TAGS', null=True)),
                ('prendido_ecommerce', models.IntegerField(blank=True, db_column='PRENDIDO_ECOMMERCE', null=True)),
                ('prendido_ean', models.IntegerField(blank=True, db_column='PRENDIDO_EAN', null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, db_column='FECHA_ACTUALIZACION', null=True)),
            ],
        ),
    ]
