# Generated by Django 3.1.4 on 2021-02-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('ean', models.CharField(blank=True, db_column='EAN', max_length=30, primary_key=True, serialize=False)),
                ('imagen_grande', models.TextField(blank=True, db_column='IMAGEN_GRANDE', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False)),
                ('Genero', models.CharField(db_column='Genero', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Genero',
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('material', models.TextField(blank=True, db_column='MATERIAL', null=True)),
                ('descripcion_material', models.TextField(blank=True, db_column='DESCRIPCION_MATERIAL', null=True)),
                ('descripcion_material_enriquecido', models.TextField(blank=True, db_column='DESCRIPCION_MATERIAL_ENRIQUECIDO', null=True)),
                ('descripcion_larga', models.TextField(blank=True, db_column='DESCRIPCION_LARGA', null=True)),
                ('ean', models.CharField(blank=True, db_column='EAN', max_length=30, primary_key=True, serialize=False)),
                ('codigo_talla', models.TextField(blank=True, db_column='CODIGO_TALLA', null=True)),
                ('descripcion_talla', models.TextField(blank=True, db_column='DESCRIPCION_TALLA', null=True)),
                ('codigo_color', models.TextField(blank=True, db_column='CODIGO_COLOR', null=True)),
                ('descripcion_color', models.TextField(blank=True, db_column='DESCRIPCION_COLOR', null=True)),
                ('imagen_pequena', models.TextField(blank=True, db_column='IMAGEN_PEQUENA', null=True)),
                ('imagen_grande', models.TextField(blank=True, db_column='IMAGEN_GRANDE', null=True)),
                ('imagen_frente', models.TextField(blank=True, db_column='IMAGEN_FRENTE', null=True)),
                ('imagen_espalda', models.TextField(blank=True, db_column='IMAGEN_ESPALDA', null=True)),
                ('imagen_detalle', models.TextField(blank=True, db_column='IMAGEN_DETALLE', null=True)),
                ('imagen_detalle2', models.TextField(blank=True, db_column='IMAGEN_DETALLE2', null=True)),
                ('modelo', models.TextField(blank=True, db_column='MODELO', null=True)),
                ('tipo_prenda', models.TextField(blank=True, db_column='TIPO_PRENDA', null=True)),
                ('subgrupo', models.TextField(blank=True, db_column='SUBGRUPO', null=True)),
                ('caracteristica', models.TextField(blank=True, db_column='CARACTERISTICA', null=True)),
                ('marca', models.TextField(blank=True, db_column='MARCA', null=True)),
                ('uso', models.TextField(blank=True, db_column='USO', null=True)),
                ('grupo_destino', models.TextField(blank=True, db_column='GRUPO_DESTINO', null=True)),
                ('genero', models.TextField(blank=True, db_column='GENERO', null=True)),
                ('departamento', models.TextField(blank=True, db_column='DEPARTAMENTO', null=True)),
                ('tags', models.TextField(blank=True, db_column='TAGS', null=True)),
                ('prendido_ecommerce', models.IntegerField(blank=True, db_column='PRENDIDO_ECOMMERCE', null=True)),
                ('prendido_ean', models.IntegerField(blank=True, db_column='PRENDIDO_EAN', null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, db_column='FECHA_ACTUALIZACION', null=True)),
                ('composicion_es', models.TextField(blank=True, db_column='COMPOSICION_ES', null=True)),
                ('tipo_material', models.TextField(blank=True, db_column='TIPO_MATERIAL', null=True)),
                ('origen', models.TextField(blank=True, db_column='ORIGEN', null=True)),
                ('url_catalogo', models.TextField(blank=True, db_column='URL_CATALOGO', null=True)),
                ('url_imagen', models.TextField(blank=True, db_column='URL_IMAGEN', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MysqlColores',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('material', models.CharField(blank=True, db_column='MATERIAL', max_length=30, null=True)),
                ('descripcion_color', models.CharField(blank=True, db_column='DESCRIPCION_COLOR', max_length=50, null=True)),
                ('icono_color', models.CharField(blank=True, db_column='ICONO_COLOR', max_length=500, null=True)),
                ('codigo_color', models.TextField(blank=True, db_column='CODIGO_COLOR', null=True)),
            ],
            options={
                'db_table': 'MYSQL_COLORES',
            },
        ),
        migrations.CreateModel(
            name='MysqlImagenes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ean', models.CharField(blank=True, db_column='EAN', max_length=30, null=True)),
                ('imagen', models.CharField(blank=True, db_column='IMAGEN', max_length=500, null=True)),
            ],
            options={
                'db_table': 'MYSQL_IMAGENES',
            },
        ),
        migrations.CreateModel(
            name='MysqlMateriales',
            fields=[
                ('material', models.CharField(db_column='MATERIAL', max_length=30, primary_key=True, serialize=False)),
                ('descripcion_material', models.CharField(blank=True, db_column='DESCRIPCION_MATERIAL', max_length=300, null=True)),
                ('imagen', models.CharField(blank=True, db_column='IMAGEN', max_length=800, null=True)),
                ('tipo_prenda', models.CharField(blank=True, db_column='TIPO_PRENDA', max_length=50, null=True)),
                ('departamento', models.CharField(blank=True, db_column='DEPARTAMENTO', max_length=50, null=True)),
                ('marca', models.CharField(blank=True, db_column='MARCA', max_length=20, null=True)),
                ('composicion_es', models.CharField(blank=True, db_column='COMPOSICION_ES', max_length=100, null=True)),
            ],
            options={
                'db_table': 'MYSQL_MATERIALES',
            },
        ),
        migrations.CreateModel(
            name='MysqlTallas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('material', models.CharField(blank=True, db_column='MATERIAL', max_length=30, null=True)),
                ('descripcion_talla', models.CharField(blank=True, db_column='DESCRIPCION_TALLA', max_length=50, null=True)),
            ],
            options={
                'db_table': 'MYSQL_TALLAS',
            },
        ),
        migrations.CreateModel(
            name='Orden_Tallas',
            fields=[
                ('id', models.CharField(db_column='Descripcion_talla', max_length=30, primary_key=True, serialize=False)),
                ('marca', models.IntegerField(db_column='Orden', null=True)),
            ],
            options={
                'db_table': 'Orden_Tallas',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Prenda',
            fields=[
                ('id', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False)),
                ('Tipo_Prenda', models.CharField(db_column='Tipo_prenda', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Tipo_Prenda',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False)),
                ('marca', models.CharField(db_column='Marca', max_length=30, null=True)),
                ('Genero', models.ManyToManyField(to='material.Genero')),
            ],
            options={
                'db_table': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Grupo_Destino',
            fields=[
                ('id', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False)),
                ('Grupo_Destino', models.CharField(db_column='Grupo_destino', max_length=50, null=True)),
                ('Tipo_Prenda', models.ManyToManyField(to='material.Tipo_Prenda')),
            ],
            options={
                'db_table': 'Grupo_Destino',
            },
        ),
        migrations.AddField(
            model_name='genero',
            name='Grupo_Destino',
            field=models.ManyToManyField(to='material.Grupo_Destino'),
        ),
        migrations.CreateModel(
            name='Catalogo_temp',
            fields=[
                ('autoincrementable', models.AutoField(db_column='autoincrementable', default=None, primary_key=True, serialize=False)),
                ('material', models.CharField(blank=True, db_column='MATERIAL', max_length=30)),
                ('unidad_empaque', models.TextField(blank=True, db_column='UNIDAD_EMPAQUE', null=True)),
                ('precio', models.TextField(blank=True, db_column='PRECIO', null=True)),
                ('moneda', models.TextField(blank=True, db_column='MONEDA', null=True)),
                ('pais', models.TextField(blank=True, db_column='PAIS', null=True)),
                ('coleccion', models.TextField(blank=True, db_column='COLECCION', null=True)),
                ('hash_uuid', models.CharField(blank=True, db_column='HASH_UUID', max_length=100, null=True)),
            ],
            options={
                'unique_together': {('material', 'hash_uuid')},
            },
        ),
    ]
