# Generated by Django 3.1.4 on 2021-07-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='instrucciones_lavado',
            field=models.TextField(blank=True, db_column='INSTRUCCIONES_LAVADO', null=True),
        ),
    ]
