# Generated by Django 3.1 on 2020-09-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_cloudimage_converts_descarga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descarga_imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='materiales',
            name='composicion_es',
            field=models.DateTimeField(blank=True, db_column='COMPOSICION_ES', null=True),
        ),
    ]
