# Generated by Django 3.1 on 2020-10-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20201022_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='id',
            field=models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grupo_destino',
            name='id',
            field=models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marca',
            name='id',
            field=models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipo_prenda',
            name='id',
            field=models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False),
        ),
    ]
