# Generated by Django 3.1.4 on 2021-07-07 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0002_materiales_instrucciones_lavado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysqlRegistro_Peticiones',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=200, primary_key=True, serialize=False)),
                ('fecha_peticion', models.DateTimeField(blank=True, db_column='FECHA_PETICION', null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, db_column='FECHA_INICIO', null=True)),
                ('fecha_terminado', models.DateTimeField(blank=True, db_column='FECHA_TERMINADO', null=True)),
                ('estado', models.CharField(blank=True, db_column='ESTADO', max_length=20, null=True)),
                ('estado_borrado', models.BooleanField(blank=True, db_column='ESTADO_BORRADO')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MYSQL_REGISTRO_PETICION',
            },
        ),
    ]
