# Generated by Django 3.1 on 2020-10-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20201022_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='modelo',
            field=models.TextField(blank=True, db_column='MODELO', null=True),
        ),
    ]
