# Generated by Django 3.1.4 on 2021-07-07 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0003_mysqlregistro_peticiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysqlregistro_peticiones',
            name='usuario',
            field=models.ForeignKey(db_column='USUARIO', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
