# Generated by Django 3.1 on 2020-09-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20200904_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo_temp',
            fields=[
                ('material', models.CharField(blank=True, db_column='MATERIAL', max_length=30, primary_key=True, serialize=False)),
                ('unidad_empaque', models.TextField(blank=True, db_column='UNIDAD_EMPAQUE', null=True)),
                ('precio', models.TextField(blank=True, db_column='PRECIO', null=True)),
                ('moneda', models.TextField(blank=True, db_column='MODENA', null=True)),
                ('pais', models.TextField(blank=True, db_column='PAIS', null=True)),
            ],
        ),
    ]
