# Generated by Django 3.1 on 2020-11-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_materiales_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysqlImagenes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ean', models.CharField(blank=True, db_column='EAN', max_length=30, null=True)),
                ('imagen', models.CharField(blank=True, db_column='IMAGEN', max_length=500, null=True)),
            ],
            options={
                'db_table': 'MYSQL_IMAGENES',
            },
        ),
    ]
