# Generated by Django 3.1 on 2020-09-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_catalogo_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo_temp',
            name='coleccion',
            field=models.TextField(blank=True, db_column='COLECCION', null=True),
        ),
    ]
