# Generated by Django 3.1 on 2020-11-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_mysqlimagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='composicion_es',
            field=models.TextField(blank=True, db_column='COMPOSICION_ES', null=True),
        ),
    ]
