# Generated by Django 3.1.4 on 2021-01-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_materiales_tipo_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='origen',
            field=models.TextField(blank=True, db_column='ORIGEN', null=True),
        ),
        migrations.AddField(
            model_name='materiales',
            name='url_catalogo',
            field=models.TextField(blank=True, db_column='URL_CATALOGO', null=True),
        ),
    ]
