# Generated by Django 3.1.4 on 2021-01-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_auto_20210113_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='url_imagen',
            field=models.TextField(blank=True, db_column='URL_IMAGEN', null=True),
        ),
    ]
