# Generated by Django 3.1 on 2021-02-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0009_materiales_url_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo_temp',
            name='hash_uuid',
            field=models.TextField(blank=True, db_column='HASH_UUID', null=True),
        ),
    ]
