# Generated by Django 3.1 on 2021-02-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0010_catalogo_temp_hash_uuid'),
    ]

    operations = [
         migrations.AlterField(
            model_name='catalogo_temp',
            name='material',
            field=models.CharField(blank=True, db_column='MATERIAL', max_length=30),
        ),
        migrations.AddField(
            model_name='catalogo_temp',
            name='autoincrementable',
            field=models.AutoField(db_column='autoincrementable', default=None, primary_key=True, serialize=False),
        ),       
        migrations.AlterUniqueTogether(
            name='catalogo_temp',
            unique_together={('material', 'hash_uuid')},
        ),
    ]
